# base image
ARG REPO_LOCATION=""
FROM ${REPO_LOCATION}ubuntu:22.04

# user
ARG USER_NAME=edgeai
ENV HOME_DIR=/opt
ENV CONDA_DIR=${HOME_DIR}/miniconda3
ENV PATH=${CONDA_DIR}/bin:$PATH

# build settings
ARG PROJECT_NAME="modelmaker"
ARG DEBIAN_FRONTEND=noninteractive
# avoid warnings/errors while installing pillow-simd
ARG LC_ALL=C.UTF-8

# proxy
ARG http_proxy=""
ARG https_proxy=""
ARG no_proxy=""

# proxy for apt
# /etc/apt/apt.conf will have to be updated if apt install is needed during docker run
# and if the proxy used is different from the proxy being used here during docker build
RUN if [ ! -z $http_proxy ]; then echo "Acquire::http::proxy \"${http_proxy}\";" > /etc/apt/apt.conf; fi && \
    if [ ! -z $https_proxy ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi

# baseline
RUN apt update && apt install -y sudo git curl iputils-ping wget cmake build-essential libgtk-3-0 apt-utils \
    libbz2-dev xz-utils libreadline-dev libncurses5-dev libssl-dev libsqlite3-dev liblzma-dev

# additional packages
RUN apt install -y libffi-dev libjpeg-dev zlib1g-dev graphviz graphviz-dev protobuf-compiler

# ##################################################################
# Method 1: these lines would have created a user and switched to it
# add user, inspired by: https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user
# RUN groupadd --gid $USER_GID $USER_NAME && \
#     useradd --uid $USER_ID --gid $USER_GID --create-home $USER_NAME && \
#     chown -R ${USER_ID}:${USER_GID} ${HOME_DIR}
#
# # not having this may cause sudo commands in our setup files to issue an error
# # but any sudo intallation required may be finished above - so it should be okay.
# RUN echo ${USER_NAME} ALL=\(root\) NOPASSWD:ALL >> /etc/sudoers.d/${USER_NAME} && chmod 400 /etc/sudoers.d/${USER_NAME}
#
# # switch user, workdir, default permissions
# USER $USER_NAME
# RUN echo "umask u=rwx,g=rx,o=rx" >> ${HOME_DIR}/.bashrc
# ##################################################################
# Method 2: continue as root. during docker run, --user argument can be used to map to the host user
# also a chmod -R ugo+rwx ${HOME_DIR} is added at the end of this file to enable such mapped users to have access.
# that permission can be later restricted to only folders where a write is required.
RUN mkdir -p ${HOME_DIR}
# ##################################################################

# change working directory
WORKDIR ${HOME_DIR}


RUN apt update && apt install -y \
    sudo curl wget git bzip2 build-essential \
    libglib2.0-0 libxext6 libsm6 libxrender1 ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Miniconda 설치
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    mkdir -p ${CONDA_DIR} && \
    bash /tmp/miniconda.sh -b -f -p ${CONDA_DIR} && \
    rm /tmp/miniconda.sh && \
    conda clean -afy

# pyenv works with bash, so change shell to bash
SHELL ["/bin/bash", "--login", "-c"]


# Conda 가상환경 생성 및 ToS 수락
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    conda update -n base -c defaults conda && \
    conda init && \
    conda create -y -n py310 python=3.10

# Conda 환경 경로 우선 적용 (activate 안 써도 됨)
ENV PATH="${CONDA_DIR}/envs/py310/bin:$PATH"

RUN pip install --no-input --upgrade pip setuptools && \
    pip install --no-input --upgrade wheel cython numpy

# 작업 경로 설정
WORKDIR ${HOME_DIR}

# # update pip setuptools
# RUN source ${HOME_DIR}/.bashrc && \
#     pip install --no-input --upgrade pip setuptools && \
#     pip install --no-input --upgrade wheel cython numpy

# Note 1: this can be reversed later as a last step after all installations are done.
# enabling write permissions for all users, if support is needed for users passed via --user argument of docker run
RUN chmod -R ugo+rwx ${HOME_DIR}

# Note 2: after all installations are done,
# it is possible to remove the file /etc/sudoers.d/${USER_NAME} (if that was used above)

# Note 3: in the container, .bashrc or .pyenvrc may need to be sourced to activate the Python environment
# if it is not being activated automatically.
# source ${HOME_DIR}/.bashrc

